### PR TITLE
Vacuum min

### PR DESCRIPTION
**Pull request by sfsyunusSLAC**
DEV: minimalist version of original code from Cosylab includes:

- calls to all devices
- basic interlocks

### CODE REVIEW

**Comment by sfsyunusSLAC** [comment]
@klauer halp where are my style checks and pre-commits failing? I linted pragmas successfully and removed trailing white spaces to my knowledge

**Comment by klauer** [comment]
Bunch o' leading tabs and related issues - that's what the style checks are after.
At first glance, the text here looks unreadable but it is actually pretty helpful - https://travis-ci.com/github/pcdshub/lcls-plc-las-bts/jobs/477422161

Easiest way to get those fixed is to run `pre-commit install; pre-commit run --all-files`. Only caveat is it's not so easy to do that on the programming node just yet. Using psbuild it should be pretty straightforward though.

**Comment by sfsyunusSLAC** [comment]
Just found the docs on how to do this properly https://github.com/pcdshub/pre-commit-hooks/blob/master/README.md
Sorry for premature cry for help :p

**Comment by sfsyunusSLAC** [comment]
Huzzah! Look at that, CI works when you set it up right, thanks @klauer

**Pull request merged**
